global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "clients"
    static_configs:
      - targets: ["musicpresence-client-proxy_loon-clients:8080"]
  - job_name: "proxy"
    static_configs:
      - targets: ["musicpresence-client-proxy_loon-proxy:8080"]
  - job_name: "redis"
    static_configs:
      - targets: ["musicpresence-client-proxy_redis-metrics:9121"]
